export const appointmentExcelFieldLabels = {
  appointmentNo: "预约编号",
  showroom: "展厅",
  visitDate: "参观日期",
  visitTimeSlot: "参观时间段",
  visitorCount: "参观人数",
  contactName: "联系人姓名",
  contactPhone: "联系电话",
  companyName: "公司名称",
  position: "职务",
  province: "所属省份",
  internalContactInfo: "内部对接人",
  customerLevel: "来访客户级别",
  mainVisitorInfo: "主要来访人员信息",
  customerType: "客户类型",
  interestAreas: "关注方向",
  needSolutionConsulting: "是否需要方案交流",
  needGuide: "是否需要讲解",
  visitPurpose: "参观目的",
  customerRemark: "客户备注",
  receptionist: "接待人",
  receptionNote: "接待备注",
  actualReceptionLocation: "实际接待地点",
  visitStartTime: "到访开始时间",
  visitEndTime: "到访结束时间",
  needVehicle: "是否需要车辆接送",
  vehicleRequirement: "车辆接送具体要求",
  needAccommodation: "是否需要住宿安排",
  accommodationRequirement: "住宿具体要求",
  needDining: "是否需要宴请安排",
  diningRequirement: "宴请具体要求",
  giftPreparation: "是否需要准备礼品",
  giftRequirement: "礼品具体要求",
  receptionScheduleNote: "接待讲解安排",
  receptionPreparationNote: "接待准备事项",
  followUpNote: "跟进记录",
  status: "当前状态",
  approvedBy: "审批人",
  approvedAt: "审批时间",
  approvalOpinion: "审批意见",
  rejectReason: "拒绝原因",
  createdAt: "提交时间",
} as const;

export const appointmentExcelFields = [
  { key: "appointmentNo", label: appointmentExcelFieldLabels.appointmentNo, example: "" },
  { key: "showroom", label: appointmentExcelFieldLabels.showroom, example: "北京总部展厅" },
  { key: "visitDate", label: appointmentExcelFieldLabels.visitDate, example: "2026-06-18" },
  { key: "visitTimeSlot", label: appointmentExcelFieldLabels.visitTimeSlot, example: "上午" },
  { key: "visitorCount", label: appointmentExcelFieldLabels.visitorCount, example: "3" },
  { key: "contactName", label: appointmentExcelFieldLabels.contactName, example: "张三" },
  { key: "contactPhone", label: appointmentExcelFieldLabels.contactPhone, example: "13800000000" },
  { key: "companyName", label: appointmentExcelFieldLabels.companyName, example: "示例环保科技有限公司" },
  { key: "position", label: appointmentExcelFieldLabels.position, example: "销售经理" },
  { key: "province", label: appointmentExcelFieldLabels.province, example: "北京市" },
  { key: "internalContactInfo", label: appointmentExcelFieldLabels.internalContactInfo, example: "李四" },
  { key: "customerLevel", label: appointmentExcelFieldLabels.customerLevel, example: "重点客户" },
  { key: "mainVisitorInfo", label: appointmentExcelFieldLabels.mainVisitorInfo, example: "总经理 1 人，技术负责人 2 人" },
  { key: "customerType", label: appointmentExcelFieldLabels.customerType, example: "工业企业" },
  { key: "interestAreas", label: appointmentExcelFieldLabels.interestAreas, example: "污染源自动监控、环境监测数智化" },
  { key: "needSolutionConsulting", label: appointmentExcelFieldLabels.needSolutionConsulting, example: "需要" },
  { key: "needGuide", label: appointmentExcelFieldLabels.needGuide, example: "是" },
  { key: "visitPurpose", label: appointmentExcelFieldLabels.visitPurpose, example: "了解展厅方案和产品能力" },
  { key: "customerRemark", label: appointmentExcelFieldLabels.customerRemark, example: "客户希望重点了解平台能力" },
  { key: "receptionist", label: appointmentExcelFieldLabels.receptionist, example: "王五" },
  { key: "receptionNote", label: appointmentExcelFieldLabels.receptionNote, example: "客户由销售陪同到访" },
  { key: "actualReceptionLocation", label: appointmentExcelFieldLabels.actualReceptionLocation, example: "北京总部展厅一层" },
  { key: "visitStartTime", label: appointmentExcelFieldLabels.visitStartTime, example: "2026-06-18 09:30" },
  { key: "visitEndTime", label: appointmentExcelFieldLabels.visitEndTime, example: "2026-06-18 11:30" },
  { key: "needVehicle", label: appointmentExcelFieldLabels.needVehicle, example: "不需要" },
  { key: "vehicleRequirement", label: appointmentExcelFieldLabels.vehicleRequirement, example: "" },
  { key: "needAccommodation", label: appointmentExcelFieldLabels.needAccommodation, example: "不需要" },
  { key: "accommodationRequirement", label: appointmentExcelFieldLabels.accommodationRequirement, example: "" },
  { key: "needDining", label: appointmentExcelFieldLabels.needDining, example: "待确认" },
  { key: "diningRequirement", label: appointmentExcelFieldLabels.diningRequirement, example: "" },
  { key: "giftPreparation", label: appointmentExcelFieldLabels.giftPreparation, example: "待确认" },
  { key: "giftRequirement", label: appointmentExcelFieldLabels.giftRequirement, example: "" },
  { key: "receptionScheduleNote", label: appointmentExcelFieldLabels.receptionScheduleNote, example: "安排展厅讲解 30 分钟" },
  { key: "receptionPreparationNote", label: appointmentExcelFieldLabels.receptionPreparationNote, example: "提前准备产品资料" },
  { key: "followUpNote", label: appointmentExcelFieldLabels.followUpNote, example: "" },
  { key: "status", label: appointmentExcelFieldLabels.status, example: "" },
  { key: "approvedBy", label: appointmentExcelFieldLabels.approvedBy, example: "" },
  { key: "approvedAt", label: appointmentExcelFieldLabels.approvedAt, example: "" },
  { key: "approvalOpinion", label: appointmentExcelFieldLabels.approvalOpinion, example: "" },
  { key: "rejectReason", label: appointmentExcelFieldLabels.rejectReason, example: "" },
  { key: "createdAt", label: appointmentExcelFieldLabels.createdAt, example: "" },
] as const;

export const appointmentExcelHeaders = appointmentExcelFields.map((field) => field.label);
export const appointmentExcelExampleRow = appointmentExcelFields.map((field) => field.example);
